spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/Desktop/study/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth
  mustache:
    suffix: .html
    prefix: classpath:/templates/
  resources:
    static-locations: "classpath:/resources/,classpath:/templates/,classpath:/static/,/"

logging:
  level:
    web: DEBUG





