spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 66701880544-lj5je91n3clllgdtut9jduj2444l2sh8.apps.googleusercontent.com
            clientSecret: L8hc8ILUnoQQpmO8yqK0btM-
  profiles:
    include: oauth

